In [10]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn import tree
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

In [ ]:
df = pd.read_csv("salaries.csv")
df.head()

  company                  job     degree  salary_more_then_100k
0  google      sales executive  bachelors                      0
1  google      sales executive    masters                      0
2  google     business manager  bachelors                      1
3  google     business manager    masters                      1
4  google  computer programmer  bachelors                      0

In [3]:
input = df.drop("salary_more_then_100k", axis="columns")
input.head()

  company                  job     degree
0  google      sales executive  bachelors
1  google      sales executive    masters
2  google     business manager  bachelors
3  google     business manager    masters
4  google  computer programmer  bachelors

In [5]:
target = df["salary_more_then_100k"]
target.head()

0    0
1    0
2    1
3    1
4    0
Name: salary_more_then_100k, dtype: int64

In [7]:
le_comapny = LabelEncoder()
le_job = LabelEncoder()
le_degree = LabelEncoder()

In [8]:
input["company"] = le_comapny.fit_transform(input["company"])
input["job"] = le_job.fit_transform(input["job"])
input["degree"] = le_degree.fit_transform(input["degree"])
input.head()

   company  job  degree
0        2    2       0
1        2    2       1
2        2    0       0
3        2    0       1
4        2    1       0

In [11]:
tree_model = tree.DecisionTreeClassifier()
x_train,x_test,y_train,y_test = train_test_split(input, target, test_size=0.2, random_state=42)
x_train,x_test,y_train,y_test

(    company  job  degree
 13        1    0       1
 11        1    2       1
 8         0    0       0
 9         0    0       1
 2         2    0       0
 15        1    1       1
 4         2    1       0
 7         0    1       0
 10        1    2       0
 12        1    0       0
 3         2    0       1
 6         0    2       1,
     company  job  degree
 0         2    2       0
 1         2    2       1
 5         2    1       1
 14        1    1       0,
 13    1
 11    1
 8     0
 9     1
 2     1
 15    1
 4     0
 7     0
 10    1
 12    1
 3     1
 6     0
 Name: salary_more_then_100k, dtype: int64,
 0     0
 1     0
 5     1
 14    1
 Name: salary_more_then_100k, dtype: int64)

In [12]:
len(x_train),len(x_test),len(y_train),len(y_test)

(12, 4, 12, 4)

In [13]:
tree_model = tree.DecisionTreeClassifier()
tree_model.fit(x_train, y_train)

DecisionTreeClassifier()

In [14]:
tree_model.predict(x_test)

array([0, 0, 0, 1])

In [15]:
tree_model.score(x_test, y_test)

0.75

In [17]:
tree_model.predict([[2,0,1]])

c:\Users\Niloy\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array([1])

In [19]:
df1= pd.read_csv("titanic.csv")
df1.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [20]:
df1.drop(["PassengerId", "Name", "SibSp", "Parch","Ticket", "Cabin", "Embarked"], axis="columns", inplace=True)
df1.head()

   Survived  Pclass     Sex   Age     Fare
0         0       3    male  22.0   7.2500
1         1       1  female  38.0  71.2833
2         1       3  female  26.0   7.9250
3         1       1  female  35.0  53.1000
4         0       3    male  35.0   8.0500

In [22]:
le_sex = LabelEncoder()
df1["Sex"] = le_sex.fit_transform(df1["Sex"])
df1.head()

   Survived  Pclass  Sex   Age     Fare
0         0       3    1  22.0   7.2500
1         1       1    0  38.0  71.2833
2         1       3    0  26.0   7.9250
3         1       1    0  35.0  53.1000
4         0       3    1  35.0   8.0500

In [24]:
X= df1.drop("Survived", axis="columns")
X.head()

   Pclass  Sex   Age     Fare
0       3    1  22.0   7.2500
1       1    0  38.0  71.2833
2       3    0  26.0   7.9250
3       1    0  35.0  53.1000
4       3    1  35.0   8.0500

In [27]:
Y= df1["Survived"]
Y.head()

0    0
1    1
2    1
3    1
4    0
Name: Survived, dtype: int64

In [28]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)
X_train.shape, X_test.shape, Y_train.shape, Y_test.shape

((712, 4), (179, 4), (712,), (179,))

In [29]:
titanic_tree_model = tree.DecisionTreeClassifier()
titanic_tree_model.fit(X_train, Y_train)

DecisionTreeClassifier()

In [30]:
titanic_tree_model.predict(X_test)

array([0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0])

In [31]:
titanic_tree_model.score(X_test, Y_test)

0.770949720670391

In [32]:
X_test.head()

     Pclass  Sex   Age     Fare
709       3    1   NaN  15.2458
439       2    1  31.0  10.5000
840       3    1  20.0   7.9250
720       2    0   6.0  33.0000
39        3    0  14.0  11.2417

In [33]:
Y_test.head()

709    1
439    0
840    0
720    1
39     1
Name: Survived, dtype: int64

In [34]:
df1

     Survived  Pclass  Sex   Age     Fare
0           0       3    1  22.0   7.2500
1           1       1    0  38.0  71.2833
2           1       3    0  26.0   7.9250
3           1       1    0  35.0  53.1000
4           0       3    1  35.0   8.0500
..        ...     ...  ...   ...      ...
886         0       2    1  27.0  13.0000
887         1       1    0  19.0  30.0000
888         0       3    0   NaN  23.4500
889         1       1    1  26.0  30.0000
890         0       3    1  32.0   7.7500

[891 rows x 5 columns]

In [ ]:
df1.groupby("Survived").mean(numeric_only=True)

            Pclass       Sex        Age       Fare
Survived
0         2.531876  0.852459  30.626179  22.117887
1         1.950292  0.318713  28.343690  48.395408

: